/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JewelleryIndexRouteImport } from './routes/jewellery/index'
import { Route as JewellerySlugRouteImport } from './routes/jewellery/$slug'
import { Route as JewelleryAmaraRouteImport } from './routes/jewellery/amara'
import { Route as JewelleryWorkbenchRouteImport } from './routes/jewellery/workbench'
import { Route as ObjectsIndexRouteImport } from './routes/objects/index'
import { Route as ObjectsSlugRouteImport } from './routes/objects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryIndexRoute = JewelleryIndexRouteImport.update({
  id: '/jewellery/',
  path: '/jewellery/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewellerySlugRoute = JewellerySlugRouteImport.update({
  id: '/jewellery/$slug',
  path: '/jewellery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryAmaraRoute = JewelleryAmaraRouteImport.update({
  id: '/jewellery/amara',
  path: '/jewellery/amara',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryWorkbenchRoute = JewelleryWorkbenchRouteImport.update({
  id: '/jewellery/workbench',
  path: '/jewellery/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsSlugRoute = ObjectsSlugRouteImport.update({
  id: '/objects/$slug',
  path: '/objects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jewellery/$slug': typeof JewellerySlugRoute
  '/jewellery/amara': typeof JewelleryAmaraRoute
  '/jewellery/workbench': typeof JewelleryWorkbenchRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/jewellery/': typeof JewelleryIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jewellery/$slug': typeof JewellerySlugRoute
  '/jewellery/amara': typeof JewelleryAmaraRoute
  '/jewellery/workbench': typeof JewelleryWorkbenchRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/jewellery': typeof JewelleryIndexRoute
  '/objects': typeof ObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jewellery/$slug': typeof JewellerySlugRoute
  '/jewellery/amara': typeof JewelleryAmaraRoute
  '/jewellery/workbench': typeof JewelleryWorkbenchRoute
  '/objects/$slug': typeof ObjectsSlugRoute
  '/jewellery/': typeof JewelleryIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jewellery/$slug'
    | '/jewellery/amara'
    | '/jewellery/workbench'
    | '/objects/$slug'
    | '/jewellery/'
    | '/objects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jewellery/$slug'
    | '/jewellery/amara'
    | '/jewellery/workbench'
    | '/objects/$slug'
    | '/jewellery'
    | '/objects'
  id:
    | '__root__'
    | '/'
    | '/jewellery/$slug'
    | '/jewellery/amara'
    | '/jewellery/workbench'
    | '/objects/$slug'
    | '/jewellery/'
    | '/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JewellerySlugRoute: typeof JewellerySlugRoute
  JewelleryAmaraRoute: typeof JewelleryAmaraRoute
  JewelleryWorkbenchRoute: typeof JewelleryWorkbenchRoute
  ObjectsSlugRoute: typeof ObjectsSlugRoute
  JewelleryIndexRoute: typeof JewelleryIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/': {
      id: '/jewellery/'
      path: '/jewellery'
      fullPath: '/jewellery/'
      preLoaderRoute: typeof JewelleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/$slug': {
      id: '/jewellery/$slug'
      path: '/jewellery/$slug'
      fullPath: '/jewellery/$slug'
      preLoaderRoute: typeof JewellerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/amara': {
      id: '/jewellery/amara'
      path: '/jewellery/amara'
      fullPath: '/jewellery/amara'
      preLoaderRoute: typeof JewelleryAmaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/workbench': {
      id: '/jewellery/workbench'
      path: '/jewellery/workbench'
      fullPath: '/jewellery/workbench'
      preLoaderRoute: typeof JewelleryWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$slug': {
      id: '/objects/$slug'
      path: '/objects/$slug'
      fullPath: '/objects/$slug'
      preLoaderRoute: typeof ObjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JewellerySlugRoute: JewellerySlugRoute,
  JewelleryAmaraRoute: JewelleryAmaraRoute,
  JewelleryWorkbenchRoute: JewelleryWorkbenchRoute,
  ObjectsSlugRoute: ObjectsSlugRoute,
  JewelleryIndexRoute: JewelleryIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
